wit_bindgen::generate!({ generate_all });

// NOTE: the imports below is generated by wit_bindgen::generate, due to the
// WIT definition(s) specified in `wit`
use wasmcloud::libsql::execute::{
    execute, execute_batch, execute_transactional_batch, last_insert_rowid,
};
use wasmcloud::libsql::query::query;
use wasmcloud::libsql::types::LibsqlValue;

// NOTE: the `Guest` trait corresponds to the export of the `invoke` interface,
// namespaced to the current WIT namespace & package ("wasmcloud:examples")
use exports::wasmcloud::examples::invoke::Guest;

/// This struct must implement the all `export`ed functionality
/// in the WIT definition (see `wit/component.wit`)
struct QueryRunner;

const CREATE_TABLE_QUERY: &str = r#"
CREATE TABLE IF NOT EXISTS example (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  description text NOT NULL,
  created_at TEXT NOT NULL DEFAULT (DATETIME('now', 'localtime'))
);
"#;

/// A basic insert query
const INSERT_QUERY: &str = r#"
INSERT INTO example (description) VALUES (?1);
"#;

/// A batch insert query, which inserts multiple rows in a single query
const INSERT_QUERIES_1: &str = r#"
INSERT INTO example (description) VALUES ("batch inserted example row#1");
INSERT INTO example (description) VALUES ("batch inserted example row#2");
INSERT INTO example (description) VALUES ("batch inserted example row#3");
"#;

const INSERT_QUERIES_2: &str = r#"
INSERT INTO example (description) VALUES ("batch inserted example row#4");
INSERT INTO example (description) VALUES ("batch inserted example row#5");
INSERT INTO example (description) VALUES ("batch inserted example row#6");
"#;

/// A SELECT query, which takes the ID insert query, using Postgres `RETURNING` syntax,
/// which returns the contents of the row that was inserted
const SELECT_QUERY: &str = r#"
SELECT * FROM example WHERE id = ?1;
"#;

impl Guest for QueryRunner {
    fn call() -> String {
        // First, ensure the right table is present
        if let Err(e) = execute(CREATE_TABLE_QUERY, &[]) {
            return format!("ERROR: failed to create table: {e}");
        };

        // Insert multiple rows in a single batch
        if let Err(e) = execute_batch(INSERT_QUERIES_1) {
            return format!("ERROR: failed to batch insert rows: {e}");
        };

        // Insert multiple rows in a single transactional batch
        if let Err(e) = execute_transactional_batch(INSERT_QUERIES_2) {
            return format!("ERROR: failed to batch insert rows: {e}");
        };

        // Insert a row into the example
        if let Err(e) = execute(
            INSERT_QUERY,
            &[LibsqlValue::Text("inserted example row!".into())],
        ) {
            return format!("ERROR: failed to insert row: {e}");
        };

        // Get the last insert row ID
        let last_insert_rowid = match last_insert_rowid() {
            Ok(id) => id,
            Err(e) => return format!("ERROR: failed to get last insert row ID: {e}"),
        };

        // Do an explicit SELECT for the row we just inserted, using the ID that was returned
        //
        // NOTE: normally you would not need this SELECT, thanks to RETURNING:
        // https://www.postgresql.org/docs/current/dml-returning.html
        match query(SELECT_QUERY, &[LibsqlValue::Integer(last_insert_rowid)]) {
            Ok(rows) => format!("SUCCESS: inserted and manually retrieved new row:\n{rows:#?}"),
            Err(e) => format!("ERROR: failed to retrieve inserted row: {e}"),
        }
    }
}

export!(QueryRunner);
